# -*- ruby -*-

require "rubygems"
require "hoe"

$hoe_plugins$

Hoe.spec "$project$" do
  # HEY! If you fill these out in ~/.hoe_template/default/Rakefile.erb then
  # you'll never have to touch them again!
  # (delete this comment too, of course)

  # developer("FIX", "FIX@example.com")

  # license "MIT"
  # this should match the license in the README
end

# vim: syntax=ruby
